import Appointment from './PageObjects/Appointment'
import LoginPage from './PageObjects/LoginPage'
import Exception from './PageObjects/Exception'
import LoginDetails from './PageObjects/LoginDetails'
import Calendar from './PageObjects/Calendar'
import BookingHistory from './PageObjects/BookingHistory'
import AddPatient from './PageObjects/AddPatient'
import { callbackify } from 'util'
describe('Appointment', () => 
{
    // it('Verify booking appointment for existing patient', () => 
    // {
    //  const e=new Exception()   
    //  const login=new LoginPage()
    //  const a=new Appointment()
    //  const details=new LoginDetails()
    //  const cal=new Calendar()
    //  login.visit("dev")
    //  e.except()
    //  details.loginDetails(1)
    //  login.Checkcheckbox()
    //  login.submit()
    //  a.facilityDropdown("Facility_one")
    //  a.searchBox("sai")
    //  a.apptcalendar()
    //  a.timeselect()
    //  a.selectPatient("sai")
    //  a.selectProviderResoruceType("resource-option","Fever test")
    //  a.selectService("Blood site")
    //  a.addApptNote("hello tester")
    //  cal.selectDate("04/03/2021","09:40AM","booked")
    // })

    // it('Verify booking appointment for new patient', () => 
    // {
    //  const e=new Exception()   
    //  const login=new LoginPage()
    //  const a=new Appointment()
    //  const details=new LoginDetails()
    //  const cal=new Calendar()
    //  const add = new AddPatient()
    //  login.visit("dev")
    //  e.except()
    //  details.loginDetails(1)
    //  login.Checkcheckbox()
    //  login.submit()
    //  a.facilityDropdown("Facility_one")
    //  a.apptcalendar()
    //  a.timeselect()
    //  add.addPatient("Tester","check","11/08/1997","Male","11111111122","h12@mailnator.com")
    //  a.selectProviderResoruceType("resource-option","Fever test")
    //  a.selectService("Blood site")
    //  a.addApptNote("hello tester")
    //  cal.selectDate("01/03/2021","09:40AM","booked")
    // })

    // it('Verify validation for unique email id and phone number fields on calendar schedule', () => 
    // {
    //  const e=new Exception()   
    //  const login=new LoginPage()
    //  const a=new Appointment()
    //  const details=new LoginDetails()
    //  const cal=new Calendar()
    //  const add = new AddPatient()
    //  login.visit("dev")
    //  e.except()
    //  details.loginDetails(1)
    //  login.Checkcheckbox()
    //  login.submit()
    //  a.facilityDropdown("Facility_one")
    //  a.apptcalendar()
    //  a.timeselect()
    //  add.addPatient("Tester","check","11/08/1997","Male","11111111122","tes105521@gmail.com")
    //  a.selectProviderResoruceType("resource-option","Fever test")
    //  a.selectService("Blood site")
    //  a.addApptNote("hello tester")
    //  cal.selectDate("01/03/2021","09:40AM","booked")
    //  add.validation()
    // })

    // it('Verify if an appointment can be deleted from the calender schedule', () => 
    // {
    //  const e=new Exception()   
    //  const login=new LoginPage()
    //  const a=new Appointment()
    //  const details=new LoginDetails()
    //  const cal=new Calendar()
    //  login.visit("dev")
    //  e.except()
    //  details.loginDetails(1)
    //  login.Checkcheckbox()
    //  login.submit()
    //  a.facilityDropdown("Facility_one")
    //  a.apptcalendar()
    //  cal.selecttimeslot("0:00","24:00")
    //  a.appoimtmentdeletepopup("harish sk")
    // })

    // it('Verify if i can navigate to the patient dashboard', () => 
    // {
    //  const e=new Exception()   
    //  const login=new LoginPage()
    //  const a=new Appointment()
    //  const details=new LoginDetails()
    //  const cal=new Calendar()
    //  login.visit("dev")
    //  e.except()
    //  details.loginDetails(1)
    //  login.Checkcheckbox()
    //  login.submit()
    //  a.facilityDropdown("Facility_one")
    //  a.apptcalendar()
    //  cal.selecttimeslot("0:00","24:00")
    //  a.appoimtmentdashpopup("SAI RAJ")
    // })

    // it('Verify if an appoimtment can be updated from calendar pop-up', () => 
    // {
    //  const e=new Exception()   
    //  const login=new LoginPage()
    //  const a=new Appointment()
    //  const details=new LoginDetails()
    //  const cal=new Calendar()
    //  const b= new BookingHistory()
    //  login.visit("dev")
    //  e.except()
    //  details.loginDetails(1)
    //  login.Checkcheckbox()
    //  login.submit()
    //  a.facilityDropdown("Facility_one")
    //  a.apptcalendar()
    //  cal.selecttimeslot("0:00","24:00")
    //  a.appoimtmentupdatepopup("SAI RAJ")
    //  a.selectProviderResoruceType("provider-option","Provider One","zoom")
    //  a.selectService("Test")
    //  a.addApptNote("hello tester")
    //  b.status("Pending")
    //  cal.selecteditdate("04/03/2021","09:40AM","booked")
    // })

    // it('Verify if user can add sticky notes', () => 
    // {
    //  const e=new Exception()   
    //  const login=new LoginPage()
    //  const a=new Appointment()
    //  const details=new LoginDetails()
    //  login.visit("dev")
    //  e.except()
    //  details.loginDetails(1)
    //  login.Checkcheckbox()
    //  login.submit()
    //  a.facilityDropdown("Facility_one")
    //  a.searchBox("SAI RAJ")
    //  a.stickynotes("i am robot")
    // })

    it('Verify if i can search appointments based on selected providers', () => 
    {
     const e=new Exception()   
     const login=new LoginPage()
     const a=new Appointment()
     const details=new LoginDetails()
     const cal=new Calendar()
     login.visit("dev")
     e.except()
     details.loginDetails(1)
     login.Checkcheckbox()
     login.submit()
     a.todaysappt()
     a.searchprovider("provider one","Provider One")
     cal.selecttimeslot("0:00","24:00")
    })
})
